### ISSUE TITLE
Include default brushes/gradients

### ISSUE THREAD

**Issue by lost-RD** [Mavichist/Fountain#1]
Starting with no canvas and no brushes will put people off. Consider including a couple by default.

Another option is to include an example file that contains a basic map that you've made from scratch including brushes, effects, etc.

**Comment by emlazzarin** [comment]
Although I appreciate the flexibility of the brushes and gradients from a programmer's perspective, _requiring_ the user to write their own brushes (rather than allowing it as an add-on) creates a huge barrier to entry - you basically need to be a programmer _and_ want to build maps to approach this software.

Some sensible defaults would go a long way in making this much more accessible.

**Comment by HarrisonDempsey** [comment]
Just commenting to show support for this. An example map file that people can just mess around with and some better defaults would make this much much simpler to grok. 

At the moment, I imagine a lot of people are opening it, trying to make something happen, then giving up because there's no immediate map-creation goodness.

**Comment by DrakeShady** [comment]
Mavichist's sample brushes and code are now included in the windows download by going to:
Document -> Open -> Tutorial Samples.fdf

**Comment by DrakeShady** [comment]
Perhaps they could be moved into the repository for easy access?

**Comment by Mavichist** [comment]
I can move these to the repo if need be - I've now come to include an FDF file that has all the tutorial material in it (as DrakeShady says), including the brushes, effects, the gradient that I use on my blog and a sample render called 'Hello World'. Hopefully that will make things more accessible; at least until I put a video tutorial out there.

**Comment by lost-RD** [comment]
Please do. I'll redownload to get that FDF too, looking forward to messing around with it!
