### ISSUE TITLE
Current builds of Fountain (anything built from current code) cannot open Tutorial Samples.fdf

### ISSUE THREAD

**Issue by matneyx** [Mavichist/Fountain#10]
Even if I use the FDFConverter in the Zip file.

**Comment by Mavichist** [comment]
The latest tutorial sample file, included with the latest download, doesn't need to be parsed through the converter. Only files from before 1.4 need to be parsed.

**Comment by DaleMatthews** [comment]
I'm having this same issue. What are we supposed to see when we open the Tutorial Samples?

**Comment by Mavichist** [comment]
@dalematthews You aren't supposed to see anything at the moment Dale. When you load any file it loads all the contents into the program but doesnt select them by default. Try looking through the dropdowns after you load the sample document, everything should be there.

**Comment by DaleMatthews** [comment]
Oh, I think the assumption in this issue is that there is a render in the example file. My bad.

**Comment by Mavichist** [comment]
All cool. I'm moving house so i cant get to it at the moment, but at some point i will push a usability update that selects the smallest heightfield when you open a document. I havent done this so far because the program has to re-render the heightfields after the selected one changes, so if it selects one on loading you have to wait for it without necessarily wanting to. If we just select the smallest one though this wait should be minimal.

**Comment by matneyx** [comment]
A dismissable (through user configuration) popup that says something has successfully imported would be nice to have, too.

I'm working on saving/loading brushes (and after that, gradients and stuff) so I can handle building that popup.

**Comment by Mavichist** [comment]
Been a bit out of it for a few days so I haven't updated things in half a week or so. I've already partially completed an import/export for generators, brushes and effects, so we'll see how that goes. I still need to push my solution for adding gradients to the clipboard and merging documents.
